export const GET_GENERALSTATUS_REQUEST = 'GET_GENERALSTATUS_REQUEST';
export const GET_GENERALSTATUS_SUCCESS = 'GET_GENERALSTATUS_SUCCESS';
export const GET_GENERALSTATUS_FAIL = 'GET_GENERALSTATUS_FAIL';

export const GET_TOPPROFILES_SUCCESS = 'GET_TOPPROFILES_SUCCESS';
export const GET_TOPACTIVITIES_SUCCESS = 'GET_TOPACTIVITIES_SUCCESS';
export const GET_PROFILESTATS_SUCCESS = 'GET_PROFILESTATS_SUCCESS';
export const GET_TRAKINGCHART_SUCCESS = 'GET_TRAKINGCHART_SUCCESS'
export const GET_CHIFFRE_SUCCESS = 'GET_CHIFFRE_SUCCESS';